[package]
name = "navis-app"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
tauri = { workspace = true }
tauri-plugin-single-instance = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
navis-runtime = { path = "../navis-runtime" }
specta = { workspace = true }
specta-typescript = { workspace = true }
tauri-specta = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true }

[lints]
workspace = true
