// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openWorkspace: (slug: string) => typedError<null, AppError>(__TAURI_INVOKE("open_workspace", { slug })),
	openSettings: () => typedError<null, AppError>(__TAURI_INVOKE("open_settings")),
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: Settings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
};

/* Types */
export type AppError = { kind: "notFound"; entity: string; name: string } | { kind: "internal" };

export type Language = "en" | "es";

export type Settings = {
	theme: Theme,
	language: Language,
	opacity: number,
	schema_version: number,
};

export type Theme = "system" | "light" | "dark";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

