// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	openWorkspace: (slug: string) => typedError<null, AppError>(__TAURI_INVOKE("open_workspace", { slug })),
	openSettings: () => typedError<null, AppError>(__TAURI_INVOKE("open_settings")),
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: Settings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
};

/** Events */
export const events = {
	settingsChanged: makeEvent<SettingsChanged>("settings-changed"),
};

/* Types */
export type AppError = { kind: "notFound"; entity: string; name: string } | { kind: "internal" };

export type Language = "en" | "es";

export type Settings = {
	theme: Theme,
	language: Language,
	opacity: number,
	schema_version: number,
};

/**
 *  Broadcast after `save_settings` persists a new value, so every window can
 *  re-apply theme, language, and opacity without an extra IPC roundtrip.
 */
export type SettingsChanged = Settings;

export type Theme = "system" | "light" | "dark";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

function makeEvent<T>(name: string) {
    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, cb),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, cb),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, cb),
        emit: ((payload: T) => target.emit(name, payload) as unknown) as (T extends null ? () => Promise<void> : (payload: T) => Promise<void>)
    });

    return Object.assign(fn, base);
}

