// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	openWorkspace: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("open_workspace", { name })),
	listWorkspaces: () => typedError<Workspace[], AppError>(__TAURI_INVOKE("list_workspaces")),
	getOpenWorkspaces: () => typedError<string[], AppError>(__TAURI_INVOKE("get_open_workspaces")),
	createWorkspace: (name: string, description: string | null) => typedError<Workspace, AppError>(__TAURI_INVOKE("create_workspace", { name, description })),
	renameWorkspace: (old: string, newName: string) => typedError<Workspace, AppError>(__TAURI_INVOKE("rename_workspace", { old, newName })),
	deleteWorkspace: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_workspace", { name })),
	getWorkspace: (name: string) => typedError<Workspace, AppError>(__TAURI_INVOKE("get_workspace", { name })),
	openSettings: () => typedError<null, AppError>(__TAURI_INVOKE("open_settings")),
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	saveSettings: (settings: Settings) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { settings })),
};

/* Types */
export type AppError = { kind: "notFound"; entity: string; name: string } | { kind: "internal" };

export type Language = "en" | "es";

/**
 *  Persistent user settings stored at `~/.navis/settings.json5`.
 * 
 *  Forward-compatibility rules when evolving this struct:
 *  - **Adding a field**: include `#[serde(default = "fn")]` so old files
 *    that lack the field still deserialize cleanly.
 *  - **Renaming a field**: use `#[serde(alias = "old_name", rename = "new_name")]`
 *    so old files keep working; the next save rewrites with the new name.
 *  - **Removing a field**: just delete it from the struct. serde ignores
 *    unknown JSON fields by default.
 * 
 *  For non-trivial migrations (type changes, splits, joins) see
 *  `carlosjortiz/navis-prd#37`.
 */
export type Settings = {
	theme?: Theme,
	language?: Language,
	opacity?: number,
};

export type Theme = "system" | "light" | "dark";

/**
 *  A named container for related requests, stored as a subdirectory under
 *  `~/.navis/workspaces/<name>/`.
 * 
 *  The `name` field is NOT written to `workspace.json5` — it is derived from
 *  the directory name at load time and the separation is enforced by using the
 *  private `WorkspaceFile` struct for all disk reads and writes. Only
 *  `description` (and any future fields) live on disk.
 * 
 *  Forward-compatibility rules when evolving this struct:
 *  - **Adding a field**: include `#[serde(default)]` so files that pre-date the
 *    field still deserialize cleanly.
 *  - **Renaming a field**: use `#[serde(alias = "old_name")]` so old files keep
 *    working; the next save rewrites with the new name.
 *  - **Removing a field**: just delete it. serde ignores unknown JSON fields by
 *    default.
 * 
 *  For non-trivial migrations (type-change, split, join) see navis-prd#37.
 */
export type Workspace = {
	// The directory name under `~/.navis/workspaces/`. Populated at load time.
	name: string,
	description?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

